language: rust
os: linux
dist: focal
addons:
  apt:
    packages:
      - libssl-dev
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libblas-dev
cache: cargo
env:
  global: RUSTFLAGS='-D warnings -C link-args=-llapacke -C link-args=-lcblas'
jobs:
  include:
  - rust: 1.42.0 # Minimum Supported Rust Version
  - rust: stable
  - rust: beta
  - rust: nightly
  - name: Linting (fmt)
    before_script:
      - rustup component add rustfmt
    script:
      - cargo fmt --all -- --check
  - name: Linting (Clippy)
    before_script:
      - rustup component add clippy
    script:
      - cargo clippy --all-targets --all-features
  allow_failures:
    - rust: nightly
  fast_finish: true
# As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
# everything in one large command instead of multiple commands.
# In this way, the build stops immediately if one of the commands fails.
script: |
  cargo build --all &&
  cargo test --all
