language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
      - gfortran
      - libopenblas-dev
cache: cargo
env:
  global: RUSTFLAGS='-D warnings'
matrix:
  include:
  - rust: 1.38.0 # Minimum Supported Rust Version
  - rust: stable
  - rust: beta
  - rust: nightly
  - name: Linting (fmt)
    before_script:
      - rustup component add rustfmt
    script:
      - cargo fmt --all -- --check
  - name: Coverage
    before_script:
      - cargo install cargo-tarpaulin
    script:
      - cargo tarpaulin -v --all --run-types Tests Doctests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  allow_failures:
    - rust: nightly
  fast_finish: true
# As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
# everything in one large command instead of multiple commands.
# In this way, the build stops immediately if one of the commands fails.
script: |
  cargo build --all &&
  cargo test --all