[package]
name = "linfa-preprocessing"
version = "0.7.1"
authors = ["Sauro98 <ivadonadi98@gmail.com>"]

description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT OR Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml", "preprocessing"]
categories = ["algorithms", "mathematics", "science"]

[features]
blas = ["ndarray-linalg", "linfa/ndarray-linalg"]
serde = ["serde_crate", "ndarray/serde", "serde_regex"]

[dependencies]
linfa = { version = "0.7.1", path = "../.." }
ndarray = { version = "0.16", features = ["approx"] }
ndarray-linalg = { version = "0.17", optional = true }
linfa-linalg = { version = "0.2", default-features = false }
ndarray-stats = "0.6"
thiserror = "1.0"
approx = { version = "0.4" }
ndarray-rand = { version = "0.14" }
unicode-normalization = "0.1.8"
regex = "1.4.5"
encoding = "0.2"
sprs = { version = "0.11", default-features = false }

serde_regex = { version = "1.1", optional = true }
itertools = "0.14.0"

[dependencies.serde_crate]
package = "serde"
optional = true
version = "1.0"
default-features = false
features = ["std", "derive"]

[dev-dependencies]
linfa-datasets = { version = "0.7.1", path = "../../datasets", features = [
    "diabetes",
    "winequality",
    "generate",
] }
linfa-bayes = { version = "0.7.1", path = "../linfa-bayes" }
iai = "0.1"
curl = "0.4.35"
flate2 = "1.0.20"
tar = "0.4.33"
linfa = { version = "0.7.1", path = "../..", features = ["benchmarks"] }
criterion = "0.4.0"
statrs = "0.16.0"

# FIXME: Disabled as dataset link is broken
# [[bench]]
# name = "vectorizer_bench"
# harness = false

[[bench]]
name = "linear_scaler_bench"
harness = false

[[bench]]
name = "whitening_bench"
harness = false

[[bench]]
name = "norm_scaler_bench"
harness = false
