[package]
name = "linfa-pls"
version = "0.3.1"
edition = "2018"
authors = ["relf <remi.lafage@onera.fr>"]
description = "Partial Least Squares family methods"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["pls", "machine-learning", "linfa", "supervised"]
categories = ["algorithms", "mathematics", "science"]

[features]
default = []
serde = ["serde_crate", "ndarray/serde"]

[dependencies.serde_crate]
package = "serde"
optional = true
version = "1.0"
default-features = false
features = ["std", "derive"]

[dependencies]
ndarray = { version = "0.14", default-features=false }
ndarray-linalg = "0.13"
ndarray-stats = "0.4"
ndarray-rand = "0.13"
rand_isaac = "0.3"
num-traits = "0.2"
paste = "1.0"

linfa = { version = "0.3.1", path = "../.." }

[dev-dependencies]
linfa-datasets = { version = "0.3.1", path = "../../datasets", features = ["linnerud"] }
rand_isaac = "0.3"
approx = "0.4"
