[package]
name = "linfa-pls"
version = "0.5.0"
edition = "2018"
authors = ["relf <remi.lafage@onera.fr>"]
description = "Partial Least Squares family methods"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["pls", "machine-learning", "linfa", "supervised"]
categories = ["algorithms", "mathematics", "science"]

[features]
default = []
blas = ["ndarray-linalg", "linfa/ndarray-linalg"]
serde = ["serde_crate", "ndarray/serde"]

[dependencies.serde_crate]
package = "serde"
optional = true
version = "1.0"
default-features = false
features = ["std", "derive"]

[dependencies]
ndarray = { version = "0.15" }
ndarray-linalg-rs = { git = "https://github.com/rust-ml/ndarray-linalg-rs.git" }
ndarray-linalg = { version = "0.14", optional = true }
ndarray-stats = "0.5"
ndarray-rand = "0.14"
rand_isaac = "0.3"
num-traits = "0.2"
paste = "1.0"
thiserror = "1.0"
linfa = { version = "0.5.0", path = "../.." }

[dev-dependencies]
linfa-datasets = { version = "0.5.0", path = "../../datasets", features = ["linnerud"] }
rand_isaac = "0.3"
approx = "0.4"
