[package]
name = "linfa-pls"
version = "0.6.1"
edition = "2018"
authors = ["relf <remi.lafage@onera.fr>"]
description = "Partial Least Squares family methods"
license = "MIT OR Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["pls", "machine-learning", "linfa", "supervised"]
categories = ["algorithms", "mathematics", "science"]

[features]
default = []
blas = ["ndarray-linalg", "linfa/ndarray-linalg"]
serde = ["serde_crate", "ndarray/serde"]

[dependencies.serde_crate]
package = "serde"
optional = true
version = "1.0"
default-features = false
features = ["std", "derive"]

[dependencies]
ndarray = { version = "0.15" }
linfa-linalg = { version = "0.1", default-features = false }
ndarray-linalg = { version = "0.15", optional = true }
ndarray-stats = "0.5"
ndarray-rand = "0.14"
num-traits = "0.2"
paste = "1.0"
thiserror = "1.0"
linfa = { version = "0.7.0", path = "../.." }

[dev-dependencies]
linfa = { version = "0.7.0", path = "../..", features = ["benchmarks"] }
linfa-datasets = { version = "0.6.1", path = "../../datasets", features = ["linnerud"] }
approx = "0.4"
rand_xoshiro = "0.6"
criterion = "0.4.0"
statrs = "0.16.0"

[[bench]]
name = "pls"
harness = false
