[package]
name = "linfa-logistic"
version = "0.6.1"
authors = ["Paul KÃ¶rbitz / Google <koerbitz@google.com>"]

description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml", "linear"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
ndarray = { version = "0.15", features = ["approx"] }
ndarray-stats = "0.5.0"
num-traits = "0.2"
argmin = { version = "0.8.1", default-features = false }
argmin-math = { version = "0.3", features = ["ndarray_v0_15", "ndarray_all"] }
serde = "1.0"
thiserror = "1.0"


linfa = { version = "0.6.1", path = "../..", features=["serde"] }

[dev-dependencies]
approx = "0.4"
linfa-datasets = { version = "0.6.1", path = "../../datasets", features = ["winequality"] }
rmp-serde = "1"
