[package]
name = "linfa-logistic"
version = "0.5.1"
authors = ["Paul KÃ¶rbitz / Google <koerbitz@google.com>"]

description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml", "linear"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
ndarray = { version = "0.15", features = ["approx", "blas"] }
ndarray-linalg = "0.14"
ndarray-stats = "0.5.0"
num-traits = "0.2"
argmin = { version = "0.4.6", features = ["ndarrayl"] }
serde = "1.0"
thiserror = "1.0"

linfa = { version = "0.5.1", path = "../..", features=["serde"] }

[dev-dependencies]
approx = "0.4"
linfa-datasets = { version = "0.5.1", path = "../../datasets", features = ["winequality"] }
