[package]
name = "linfa-linear"
version = "0.1.0"
authors = ["Paul KÃ¶rbitz / Google <koerbitz@google.com>"]
edition = "2018"
workspace = ".."

[features]
default = []
openblas = ["ndarray-linalg/openblas"]
intel-mkl = ["ndarray-linalg/intel-mkl"]
netlib = ["ndarray-linalg/netlib"]

[dependencies]
ndarray = {version = "0.13", features = ["blas", "approx"]}
ndarray-linalg = {version = "0.12", default-features = false}
ndarray-stats = {version = "0.3"}
num-traits = {version="0.2"}

[dev-dependencies]
csv = "1.1"
ndarray-csv = "0.4"
approx = "0.3.2"
flate2 = "1.0"
ndarray-linalg = {version = "0.12", features = ["openblas"]}